package org.gallant.account.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.gallant.account.entity.FundOrderType;
import org.gallant.account.entity.FundOrderTypeExample;

public interface FundOrderTypeMapper {
    long countByExample(FundOrderTypeExample example);

    int deleteByExample(FundOrderTypeExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(FundOrderType record);

    int insertSelective(FundOrderType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_order_type
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<FundOrderType> selectByExampleSelective(@Param("example") FundOrderTypeExample example, @Param("selective") FundOrderType.Column ... selective);

    List<FundOrderType> selectByExample(FundOrderTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_order_type
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    FundOrderType selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") FundOrderType.Column ... selective);

    FundOrderType selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") FundOrderType record, @Param("example") FundOrderTypeExample example);

    int updateByExample(@Param("record") FundOrderType record, @Param("example") FundOrderTypeExample example);

    int updateByPrimaryKeySelective(FundOrderType record);

    int updateByPrimaryKey(FundOrderType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_order_type
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<FundOrderType> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_order_type
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<FundOrderType> list, @Param("selective") FundOrderType.Column ... selective);
}