package org.gallant.account.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.gallant.account.entity.FundOrder;
import org.gallant.account.entity.FundOrderExample;

public interface FundOrderMapper {
    long countByExample(FundOrderExample example);

    int deleteByExample(FundOrderExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(FundOrder record);

    int insertSelective(FundOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<FundOrder> selectByExampleSelective(@Param("example") FundOrderExample example, @Param("selective") FundOrder.Column ... selective);

    List<FundOrder> selectByExample(FundOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    FundOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") FundOrder.Column ... selective);

    FundOrder selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") FundOrder record, @Param("example") FundOrderExample example);

    int updateByExample(@Param("record") FundOrder record, @Param("example") FundOrderExample example);

    int updateByPrimaryKeySelective(FundOrder record);

    int updateByPrimaryKey(FundOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<FundOrder> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<FundOrder> list, @Param("selective") FundOrder.Column ... selective);
}