package org.gallant.account.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FundOrderExample {
    protected String orderByClause;

    protected boolean distinct;

    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fund_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    protected Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fund_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    protected Integer rows;

    public FundOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public FundOrderExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public FundOrderExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        rows = null;
        offset = null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Integer getOffset() {
        return this.offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setRows(Integer rows) {
        this.rows = rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Integer getRows() {
        return this.rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public FundOrderExample limit(Integer rows) {
        this.rows = rows;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public FundOrderExample limit(Integer offset, Integer rows) {
        this.offset = offset;
        this.rows = rows;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public FundOrderExample page(Integer page, Integer pageSize) {
        this.offset = page * pageSize;
        this.rows = pageSize;
        return this;
    }

    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFundOrderDateIsNull() {
            addCriterion("fund_order_date is null");
            return (Criteria) this;
        }

        public Criteria andFundOrderDateIsNotNull() {
            addCriterion("fund_order_date is not null");
            return (Criteria) this;
        }

        public Criteria andFundOrderDateEqualTo(Integer value) {
            addCriterion("fund_order_date =", value, "fundOrderDate");
            return (Criteria) this;
        }

        public Criteria andFundOrderDateNotEqualTo(Integer value) {
            addCriterion("fund_order_date <>", value, "fundOrderDate");
            return (Criteria) this;
        }

        public Criteria andFundOrderDateGreaterThan(Integer value) {
            addCriterion("fund_order_date >", value, "fundOrderDate");
            return (Criteria) this;
        }

        public Criteria andFundOrderDateGreaterThanOrEqualTo(Integer value) {
            addCriterion("fund_order_date >=", value, "fundOrderDate");
            return (Criteria) this;
        }

        public Criteria andFundOrderDateLessThan(Integer value) {
            addCriterion("fund_order_date <", value, "fundOrderDate");
            return (Criteria) this;
        }

        public Criteria andFundOrderDateLessThanOrEqualTo(Integer value) {
            addCriterion("fund_order_date <=", value, "fundOrderDate");
            return (Criteria) this;
        }

        public Criteria andFundOrderDateIn(List<Integer> values) {
            addCriterion("fund_order_date in", values, "fundOrderDate");
            return (Criteria) this;
        }

        public Criteria andFundOrderDateNotIn(List<Integer> values) {
            addCriterion("fund_order_date not in", values, "fundOrderDate");
            return (Criteria) this;
        }

        public Criteria andFundOrderDateBetween(Integer value1, Integer value2) {
            addCriterion("fund_order_date between", value1, value2, "fundOrderDate");
            return (Criteria) this;
        }

        public Criteria andFundOrderDateNotBetween(Integer value1, Integer value2) {
            addCriterion("fund_order_date not between", value1, value2, "fundOrderDate");
            return (Criteria) this;
        }

        public Criteria andAccountInfoIdIsNull() {
            addCriterion("account_info_id is null");
            return (Criteria) this;
        }

        public Criteria andAccountInfoIdIsNotNull() {
            addCriterion("account_info_id is not null");
            return (Criteria) this;
        }

        public Criteria andAccountInfoIdEqualTo(Integer value) {
            addCriterion("account_info_id =", value, "accountInfoId");
            return (Criteria) this;
        }

        public Criteria andAccountInfoIdNotEqualTo(Integer value) {
            addCriterion("account_info_id <>", value, "accountInfoId");
            return (Criteria) this;
        }

        public Criteria andAccountInfoIdGreaterThan(Integer value) {
            addCriterion("account_info_id >", value, "accountInfoId");
            return (Criteria) this;
        }

        public Criteria andAccountInfoIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("account_info_id >=", value, "accountInfoId");
            return (Criteria) this;
        }

        public Criteria andAccountInfoIdLessThan(Integer value) {
            addCriterion("account_info_id <", value, "accountInfoId");
            return (Criteria) this;
        }

        public Criteria andAccountInfoIdLessThanOrEqualTo(Integer value) {
            addCriterion("account_info_id <=", value, "accountInfoId");
            return (Criteria) this;
        }

        public Criteria andAccountInfoIdIn(List<Integer> values) {
            addCriterion("account_info_id in", values, "accountInfoId");
            return (Criteria) this;
        }

        public Criteria andAccountInfoIdNotIn(List<Integer> values) {
            addCriterion("account_info_id not in", values, "accountInfoId");
            return (Criteria) this;
        }

        public Criteria andAccountInfoIdBetween(Integer value1, Integer value2) {
            addCriterion("account_info_id between", value1, value2, "accountInfoId");
            return (Criteria) this;
        }

        public Criteria andAccountInfoIdNotBetween(Integer value1, Integer value2) {
            addCriterion("account_info_id not between", value1, value2, "accountInfoId");
            return (Criteria) this;
        }

        public Criteria andProductInfoIdIsNull() {
            addCriterion("product_info_id is null");
            return (Criteria) this;
        }

        public Criteria andProductInfoIdIsNotNull() {
            addCriterion("product_info_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductInfoIdEqualTo(Integer value) {
            addCriterion("product_info_id =", value, "productInfoId");
            return (Criteria) this;
        }

        public Criteria andProductInfoIdNotEqualTo(Integer value) {
            addCriterion("product_info_id <>", value, "productInfoId");
            return (Criteria) this;
        }

        public Criteria andProductInfoIdGreaterThan(Integer value) {
            addCriterion("product_info_id >", value, "productInfoId");
            return (Criteria) this;
        }

        public Criteria andProductInfoIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("product_info_id >=", value, "productInfoId");
            return (Criteria) this;
        }

        public Criteria andProductInfoIdLessThan(Integer value) {
            addCriterion("product_info_id <", value, "productInfoId");
            return (Criteria) this;
        }

        public Criteria andProductInfoIdLessThanOrEqualTo(Integer value) {
            addCriterion("product_info_id <=", value, "productInfoId");
            return (Criteria) this;
        }

        public Criteria andProductInfoIdIn(List<Integer> values) {
            addCriterion("product_info_id in", values, "productInfoId");
            return (Criteria) this;
        }

        public Criteria andProductInfoIdNotIn(List<Integer> values) {
            addCriterion("product_info_id not in", values, "productInfoId");
            return (Criteria) this;
        }

        public Criteria andProductInfoIdBetween(Integer value1, Integer value2) {
            addCriterion("product_info_id between", value1, value2, "productInfoId");
            return (Criteria) this;
        }

        public Criteria andProductInfoIdNotBetween(Integer value1, Integer value2) {
            addCriterion("product_info_id not between", value1, value2, "productInfoId");
            return (Criteria) this;
        }

        public Criteria andFundOrderTypeIdIsNull() {
            addCriterion("fund_order_type_id is null");
            return (Criteria) this;
        }

        public Criteria andFundOrderTypeIdIsNotNull() {
            addCriterion("fund_order_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andFundOrderTypeIdEqualTo(Integer value) {
            addCriterion("fund_order_type_id =", value, "fundOrderTypeId");
            return (Criteria) this;
        }

        public Criteria andFundOrderTypeIdNotEqualTo(Integer value) {
            addCriterion("fund_order_type_id <>", value, "fundOrderTypeId");
            return (Criteria) this;
        }

        public Criteria andFundOrderTypeIdGreaterThan(Integer value) {
            addCriterion("fund_order_type_id >", value, "fundOrderTypeId");
            return (Criteria) this;
        }

        public Criteria andFundOrderTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("fund_order_type_id >=", value, "fundOrderTypeId");
            return (Criteria) this;
        }

        public Criteria andFundOrderTypeIdLessThan(Integer value) {
            addCriterion("fund_order_type_id <", value, "fundOrderTypeId");
            return (Criteria) this;
        }

        public Criteria andFundOrderTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("fund_order_type_id <=", value, "fundOrderTypeId");
            return (Criteria) this;
        }

        public Criteria andFundOrderTypeIdIn(List<Integer> values) {
            addCriterion("fund_order_type_id in", values, "fundOrderTypeId");
            return (Criteria) this;
        }

        public Criteria andFundOrderTypeIdNotIn(List<Integer> values) {
            addCriterion("fund_order_type_id not in", values, "fundOrderTypeId");
            return (Criteria) this;
        }

        public Criteria andFundOrderTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("fund_order_type_id between", value1, value2, "fundOrderTypeId");
            return (Criteria) this;
        }

        public Criteria andFundOrderTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("fund_order_type_id not between", value1, value2, "fundOrderTypeId");
            return (Criteria) this;
        }

        public Criteria andFundOrderAmountIsNull() {
            addCriterion("fund_order_amount is null");
            return (Criteria) this;
        }

        public Criteria andFundOrderAmountIsNotNull() {
            addCriterion("fund_order_amount is not null");
            return (Criteria) this;
        }

        public Criteria andFundOrderAmountEqualTo(BigDecimal value) {
            addCriterion("fund_order_amount =", value, "fundOrderAmount");
            return (Criteria) this;
        }

        public Criteria andFundOrderAmountNotEqualTo(BigDecimal value) {
            addCriterion("fund_order_amount <>", value, "fundOrderAmount");
            return (Criteria) this;
        }

        public Criteria andFundOrderAmountGreaterThan(BigDecimal value) {
            addCriterion("fund_order_amount >", value, "fundOrderAmount");
            return (Criteria) this;
        }

        public Criteria andFundOrderAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("fund_order_amount >=", value, "fundOrderAmount");
            return (Criteria) this;
        }

        public Criteria andFundOrderAmountLessThan(BigDecimal value) {
            addCriterion("fund_order_amount <", value, "fundOrderAmount");
            return (Criteria) this;
        }

        public Criteria andFundOrderAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("fund_order_amount <=", value, "fundOrderAmount");
            return (Criteria) this;
        }

        public Criteria andFundOrderAmountIn(List<BigDecimal> values) {
            addCriterion("fund_order_amount in", values, "fundOrderAmount");
            return (Criteria) this;
        }

        public Criteria andFundOrderAmountNotIn(List<BigDecimal> values) {
            addCriterion("fund_order_amount not in", values, "fundOrderAmount");
            return (Criteria) this;
        }

        public Criteria andFundOrderAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fund_order_amount between", value1, value2, "fundOrderAmount");
            return (Criteria) this;
        }

        public Criteria andFundOrderAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fund_order_amount not between", value1, value2, "fundOrderAmount");
            return (Criteria) this;
        }

        public Criteria andIsActiveIsNull() {
            addCriterion("is_active is null");
            return (Criteria) this;
        }

        public Criteria andIsActiveIsNotNull() {
            addCriterion("is_active is not null");
            return (Criteria) this;
        }

        public Criteria andIsActiveEqualTo(Boolean value) {
            addCriterion("is_active =", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveNotEqualTo(Boolean value) {
            addCriterion("is_active <>", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveGreaterThan(Boolean value) {
            addCriterion("is_active >", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_active >=", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveLessThan(Boolean value) {
            addCriterion("is_active <", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveLessThanOrEqualTo(Boolean value) {
            addCriterion("is_active <=", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveIn(List<Boolean> values) {
            addCriterion("is_active in", values, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveNotIn(List<Boolean> values) {
            addCriterion("is_active not in", values, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveBetween(Boolean value1, Boolean value2) {
            addCriterion("is_active between", value1, value2, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_active not between", value1, value2, "isActive");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }
    }

    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table fund_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private FundOrderExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table fund_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        protected Criteria(FundOrderExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table fund_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public FundOrderExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table fund_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This interface was generated by MyBatis Generator.
         * This interface corresponds to the database table fund_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table fund_order
             *
             * @mbg.generated
             * @project https://github.com/itfsw/mybatis-generator-plugin
             */
            Criteria add(Criteria add);
        }
    }

    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}